server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: mysql
    url: jdbc:mysql://localhost:3306/foodware
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true